version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]

volumes:
  keycloak_data:
