version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
    entrypoint: [ "/bin/sh", "-c", "/opt/keycloak/bin/kc.sh start-dev --import-realm && /opt/keycloak/import-client-scope.sh" ]

volumes:
  keycloak_data:
