server:
  port: 8081
logging:
  level:
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springsecurity
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/springsecurity
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: EzXmqbdQrd7YD4jJ7Uuwl3ZnrtRvrb7g
            scope: openid


